/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import Form.Form_ContasReceber;
import Form.Form_GrupoProduto;
import Form.Form_Home;
import Form.Form_Marca;
import Form.Form_Produto;
import Form.Form_Venda;
import evento.EventMenuSelected;
import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JComponent;

/**
 *
 * @author mathe
 */
public class Vendas extends javax.swing.JFrame {

   private Form_Home home;
   private Form_Venda venda;
   private Form_ContasReceber contasreceber;
   private Form_GrupoProduto grp;
   private Form_Marca marca;
   private Form_Produto produto;

   
    public Vendas() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        home = new Form_Home();
        venda = new Form_Venda();
        contasreceber = new Form_ContasReceber();
        grp = new Form_GrupoProduto();
        marca = new Form_Marca();
        produto = new Form_Produto();
        menuVenda.initMoving(this);
         menuVenda.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
               if (index == 0) {
                    setForm(home);
                    }else if (index == 2){
                    setForm(grp);
                    }else if (index == 3){
                    setForm(marca);
                    }else if (index == 4){
                    setForm(produto);
                    }else if (index == 5){
                    setForm(venda);
                    }else if (index == 6){
                    setForm(contasreceber);
                }else if (index == 7){
                    dispose();
                    TelaLogin login = new TelaLogin();
                    login.setLocationRelativeTo(login);
                    login.setVisible(true);
                }else if (index == 8){
                    System.exit(WIDTH);
                }
            }
        });
        //  set when system open start with home form
        setForm(new Form_Home());
    }
    
     private void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuVenda = new coomponete.MenuVenda();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(47, 59, 78));
        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(menuVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1382, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)
            .addComponent(menuVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private coomponete.MenuVenda menuVenda;
    // End of variables declaration//GEN-END:variables
}
